### ISSUE TITLE
Paragraph block: Italics differs in editor from frontend

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#15]
_When formatting the props section in italics, the editor shows it in bold and italics._ 
![Screen Shot 2022-11-17 at 16 08 00](https://user-images.githubusercontent.com/39980/202560340-ec76bbd4-0578-42aa-9b59-053f150b118f.png)
![Screen Shot 2022-11-17 at 16 08 10](https://user-images.githubusercontent.com/39980/202560345-211609ab-e9ce-411a-ad54-ba880342a1d3.png)

_It is rendered correctly on the front end._ 
![Screen Shot 2022-11-17 at 16 08 24](https://user-images.githubusercontent.com/39980/202560434-089d1e7e-8cff-4107-9608-8dda547a8140.png)

**Comment by ryelle** [comment]
Findings while debugging this: For some reason, a version of Inter italic is being loading from the social image generator plugin, but it's `inter-900-italic.woff2` — so it's 900 weight. On the frontend, no italics are loaded, so the browser does faux-italics. We need to add Inter italics to the global available fonts.

**Comment by ryelle** [comment]
Marking this as "Blocked" because the fix needs to happen in wporg-mu-plugins: https://github.com/WordPress/wporg-mu-plugins/issues/303. Once that's fixed, this can be re-checked but likely it will just work :)

**Comment by outdoor2kode** [comment]
I tried reproducing it with the following steps,

Steps:
1. Go to https://developer.wordpress.org/news/wp-admin/post.php?post=696&action=edit
2. Scroll down to the bottom and find the `props to ...`. Italicize it.

but I found that I couldn’t reproduce it as how this issue was described - after formatting the props in `italics`, it would show `bold` and `italics`.
I can only see `italics` no matter if I clicked italics or not.
![bold](https://user-images.githubusercontent.com/18050944/212931222-4bdcca3a-be90-4769-8dcd-279c2af144c8.gif)

![image](https://user-images.githubusercontent.com/18050944/212933559-73e0547d-92f9-4f67-8588-1662b039839e.png)

![image](https://user-images.githubusercontent.com/18050944/212933621-a9b51be4-02aa-40ae-8b5c-0bb7b81cb974.png)

Perhaps I misunderstood or missed something and tested it in the wrong way, 
but in addition to that, I also found that there are GB options for the font appearance on the right side of the editor for the paragraph. And in the post above, `Regular Italic` was chosen. 
I’m wondering if this is the root cause of this issue?
![image](https://user-images.githubusercontent.com/18050944/212933789-d8376182-7999-4f40-9057-2dc6f94e92cd.png)



---



> Marking this as "Blocked" because the fix needs to happen in wporg-mu-plugins: https://github.com/WordPress/wporg-mu-plugins/issues/303.

I've checked again how we subset `Inter` as I remember the original `Inter.var` used for subsetting already includes italics.

First I dropped the `Inter.ttf` from the Inter folder downloaded from [the official site](https://rsms.me/inter/) on [FontDrop!](https://fontdrop.info/#/?darkmode=true.).
<img width="797" alt="image" src="https://user-images.githubusercontent.com/18050944/212931506-6c7088f4-e255-4edf-a512-4dc287b0aeee.png">

And the result shows that it supports italics:
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/18050944/212932349-3f954c3c-32bd-4fa2-8a29-58bd21ea207a.png">

Later the font subsetting was done again using the script [here](https://github.com/WordPress/wporg-mu-plugins/blob/trunk/bin/font-subset.js) and the `Inter.ttf` above, it seems the resulting sizes are identical.

#### font subset in the repo
![stored](https://user-images.githubusercontent.com/18050944/212932582-7a3a9817-8845-4ebc-8396-ee37df0ff300.png)
#### new font subset output
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/18050944/212932635-4bf1a7a5-bbac-4633-86db-19c1c55faa51.png">

**Comment by ryelle** [comment]
> The original Inter.var used for subsetting already includes italics.

I thought so, but then I was able to reproduce this issue at the time (back in November), and that seemed like a viable cause.

I'm not sure what changed, but I don't see `inter-900-italic.woff2` loading anymore either, and as you mention, the block in the post is displaying correctly now.

@bph can you confirm that this issue is not happening anymore?

**Comment by bph** [comment]
Thank you @ren for testing this again. And yes, I can confirm the paragraph block formatted in italics display correctly now in the editor view. I close the issue as completed now.
