### ISSUE TITLE
dev.wp.org wide search on the front page?

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#2]
It would be great if the search box on the front page of the blog would show results from all of developer.wordpress.org site, as a path to a one-stop-show for developers.
<img width="847" alt="Screen Shot 2022-05-25 at 15 02 14" src="https://user-images.githubusercontent.com/39980/170281175-769057f2-a67a-4591-81ca-cac60de76e16.png">

**Comment by ryelle** [comment]
Do you mean a search for just `developer.wordpress.org`? We can probably do that. But it wouldn't search `developer.wordpress.org/blog`, since that's a separate WordPress site. Is that okay?

**Comment by bph** [comment]
Hmm, we probably need both. So we would need two search boxes then? one for all of developer.wordpress.org and one for the blog. Might be confusing for the reader, but if there is no other way.

**Comment by juanmaguitar** [comment]
> So we would need two search boxes then? one for all of developer.wordpress.org and one for the blog. Might be confusing for the reader [...]

I don't think having two search boxes is a good solution here. I would launch this blog as simple as we can, maintaining just a search box to search in `developer.wordpress.org/blog`

To start with, maybe we can just add some links to Developer Docs as suggested in https://github.com/WordPress/wporg-developer-blog/issues/7

**Comment by outdoor2kode** [comment]
@bph 
I'm trying to take Dev Blog out of beta, and now this issue and #33 are the last two issues we need to resolve before doing so.

I'm wondering what's your thought on @juanmaguitar's [comment](https://github.com/WordPress/wporg-developer-blog/issues/2#issuecomment-1154787185) - maintaining just a search box to search in `developer.wordpress.org/blog`? Since I believe that is what the search box on the homepage currently searches in (correct me if I'm wrong about this), if we'd like to take JuanMa's suggestion, this issue can be closed then.

But if we still want to have two search boxes or something else, not sure whether it makes sense if we could come up with a new design in [Figma](https://www.figma.com/file/2CKNK5sN7PKNXA4VjVhyqA/Dev-blog?node-id=1111%3A1084&t=ppS3cavZQMsdKaWS-0) and open a new issue for it, making it a part of the new look of the landing page that we're going to apply later on.

**Comment by bph** [comment]
Totally ok to table the documentation-wide search and close this issue. 

I missed the part where the redesign following @joen's mockup is no longer required to take the Developer Blog out of beta. 
I did read the discussion in #22 but it doesn't seem to have a decision, or am I reading this wrongly?
 @juanmaguitar

**Comment by juanmaguitar** [comment]
> I missed the part where the redesign following @joen's mockup is no longer required to take the Developer Blog out of beta. I did read the discussion in #22 but it doesn't seem to have a decision, or am I reading this wrongly? @juanmaguitar

I've asked about this here https://github.com/WordPress/wporg-developer-blog/issues/35#issuecomment-1425419139
