### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#22]
Javier Arce: 
"We shouldn’t put a search box inside the beta announcement bar. Let’s move it to the top of the Latest post section for the moment."
and "We shouldn’t put a search box inside the beta announcement bar. Let’s move it to the top of the Latest post section for the moment."

Joen Asmussen:  "The search box looks unrefined:
![Screen Shot 2022-11-21 at 09 38 25](https://user-images.githubusercontent.com/39980/203082185-1b20668c-ef88-43c0-b84b-6143fe18f848.png)
The font size is smaller inside the input than in the button, there’s no radius on either, the input border is 2px vs. 1px, and contrast doesn’t meet requirements. Might be better to show this section on a white background, or integrate it otherwise.

We don’t use a separate label for search in other places, and usually use a single input pattern, like this:
![Screen Shot 2022-11-21 at 09 38 46](https://user-images.githubusercontent.com/39980/203082274-576cee06-cf4e-4228-b083-1b3e7b6f2684.png)"

cc: @javierarce  @jasmussen

**Comment by ryelle** [comment]
Once https://github.com/WordPress/wporg-parent-2021/pull/61 lands, you should be able to use the "secondary" style on the search block to get closer to that design.

**Comment by ryelle** [comment]
I applied the "secondary" style to the search box and moved it to the top of the posts list:

![Screen Shot 2023-01-06 at 12 19 17](https://user-images.githubusercontent.com/541093/211063968-b3643e09-0545-47d5-9d4e-ad9f5f5d1893.png)

**Comment by bph** [comment]
Thanks @ryelle for updating the search box.

**Comment by ryelle** [comment]
@bph Does that fix this issue enough or is more work needed here? If it's fixed, can you close the issue?

**Comment by bph** [comment]
Thank you, @ryelle  - It was @jasmussen who expressed concerns, so I'd love for Joen to chime in here and on the [subscribe issue](https://github.com/WordPress/wporg-developer-blog/issues/21) as well.

**Comment by jasmussen** [comment]
The search box looks better, yes, but it's not entirely as it looks on other redesigns. For example the [Showcase](https://wordpress.org/showcase/) was recently redesigned to have this new style of search box:

<img width="466" alt="Screenshot 2023-01-13 at 13 57 38" src="https://user-images.githubusercontent.com/1204802/212325469-5ae502fb-7734-479f-9a02-43a9ec4b9f74.png">

The text inside there is actually a little small, and [the Figma WP.org design library](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=1040%3A2884&t=VydBUTdR7qL1AiCm-1) remains a better source of truth:

<img width="222" alt="Screenshot 2023-01-13 at 13 59 26" src="https://user-images.githubusercontent.com/1204802/212325800-49ef2806-a552-4dfa-9ff5-70e7f42de39c.png">

So it isn't just about making sure the border radius, color, font, font size are right, it's also about the width of the box and where it's placed. Right now it seems randomly placed above the post list, whereas both theme directory and pattern directory have them in consistent places similar to that of the Showcase:
<img width="1217" alt="Screenshot 2023-01-13 at 14 01 00" src="https://user-images.githubusercontent.com/1204802/212326265-969b50c5-425a-4f18-b231-3134f4063d29.png">

<img width="1256" alt="Screenshot 2023-01-13 at 14 02 14" src="https://user-images.githubusercontent.com/1204802/212326272-8607e676-5b40-4bb6-93b8-abab060e7852.png">

It's the same issue with the newsletter subscription box, it doesn't look like it does on /news.

So the primary issue is that the design appears to be diverging for what I understand to be mostly technical reasons. I understand the blog was built on the assumption that it could reuse the /news theme mostly verbatim, so the main challenge here is to get those two to actually align more.

**Comment by outdoor2kode** [comment]
Hi @jasmussen,

I'm taking over the issue, and by reading through the thread discussion, I got some questions I'd like to ask for further clarification to see if my understanding of it is correct.

- The search box in https://developer.wordpress.org/news/ doesn't align with the one in [the Figma WP.org design library](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=1040%3A2884&t=VydBUTdR7qL1AiCm-1). It should be shorter and be refined more?
- As for where it should be placed, I'm wondering if we already had a design for it somewhere, or it still needs some further discussion. 
#### Search box in developer-blog
<img width="3144" alt="image" src="https://user-images.githubusercontent.com/18050944/215986770-c3b91184-a47e-4b27-bf44-f093fe908eb2.png">

---

> the newsletter subscription box, it doesn't look like it does on /news.

Not sure if I understand it correctly, are the following two imgs the newsletter subscription box we'd like to compare? I don't see much difference between them. It does have a little discrepancy for the `subscribe` button width and font weight, is this the point you'd like to highlight? Or it's something else that I totally missed.

#### Newsletter subscription box on developer-blog
<img width="774" alt="image" src="https://user-images.githubusercontent.com/18050944/215989445-13894615-f256-41e4-b3f1-413341e7fe63.png">

#### Newsletter subscription box on news
<img width="782" alt="image" src="https://user-images.githubusercontent.com/18050944/215989651-d0fc7ded-2e08-45b5-ad45-db39f24ce0fe.png">

Thanks!

cc @bph

**Comment by jasmussen** [comment]
Thank you for the attention to detail. Yes, the boxes feels much closer now, nice work. The "Subscribe" text is still bolder, but that's a small thing that if fixed can close this issue.

On a separate note, I have put together a small refresh of the dev blog:

![Dev blog](https://user-images.githubusercontent.com/1204802/216000388-189a7fc9-b3aa-4346-95fa-2dae00a010f9.png)

[Figma](https://www.figma.com/file/2CKNK5sN7PKNXA4VjVhyqA/Dev-blog?node-id=1111%3A1084&t=d8S1prCk44p6i1ae-1)

The idea is to reuse the design from the Developer site that's also being redesigned. What's the best way to share this design? New issue here? And would this simplify the site design work, being able to re-apply ideally the same theme that the developer site will get?

**Comment by bengreeley** [comment]
@jasmussen I think a new issue would be the right next step. Given the potential tweaks to the Developer site design that were recently discussed, I'm thinking we may want to hold off on the implementation of this new look of the developer blog until that gets settled. What are your thoughts?

Since we're looking to change the landing page significantly down the road anyways, my suggestion is we apply these light updates that @renintw made so the site can come out of beta, and then we can apply the new look to the landing page later on. If we did that, I wonder if we should pause any work on these issues which are homepage-specific and focus on wrapping up the rest of the tasks to take it out of beta:

* https://github.com/WordPress/wporg-developer-blog/issues/30
* https://github.com/WordPress/wporg-developer-blog/issues/23 (reusing grid from news page)

**Comment by jasmussen** [comment]
Created a new issue here https://github.com/WordPress/wporg-developer-blog/issues/35

**Comment by outdoor2kode** [comment]
> The "Subscribe" text is still bolder, but that's a small thing that if fixed can close this issue.

Based on [Figma](https://www.figma.com/file/2CKNK5sN7PKNXA4VjVhyqA/Dev-blog?node-id=1111%3A1084&t=d8S1prCk44p6i1ae-1), it seems the bolder font on Developer Blog is the right one and the thinner font on the News isn't. After looking into it, found out that this is because the button font weight on Dev Blog is affected by the wprog-parent theme, and since the development of News didn't involve wporg-parent, so the button style is a bit off.

This can be fixed by specifically adding CSS style to tweak News button style or replacing the bottom-banner of News with the footer template of wporg-parent, but that might be some effort to do that (@ryelle correct me if I'm wrong about it, thanks!), so I'm tempted to leave it as-is on News.

Since the style of Subscribe button isn't incorrect here, and there's a new issue open for the new look of the homepage, I'm going to close this issue then.

--

As @bengreeley suggested, it seems a good idea to hold off on homepage-specific issues (#30 #23 #35) at the moment to focus on taking it out of beta, which leaves #33 #18 (PR was open) #2 (WIP, currently looking for some clarifications) to do, and after these issues being wrapped up, we can proceed to next step.
