### ISSUE TITLE
TOC links go 404 

### ISSUE THREAD

**Issue by bph** [WordPress/wporg-developer-blog#29]
On the page, [Tips and guidelines for writers](https://developer.wordpress.org/news/tips-and-guidelines-for-writers/), we use the Table of Contents- block that was converted to a static list. Now when I click on the anchor links, I get a 404 message. 
See video: 

https://user-images.githubusercontent.com/39980/204665176-e576b3d2-e3db-4d7b-b969-b5267e2cbfa6.mp4

The link looks right:
https://developer.wordpress.org/news/2022/11/18/want-to-write-for-the-developer-blog/#be-a-person-talking-to-a-person

**Comment by ryelle** [comment]
It looks like the URL for this is now `https://developer.wordpress.org/news/tips-and-guidelines-for-writers/` — was it converted from a post to a page? The URL `https://developer.wordpress.org/news/2022/11/18/want-to-write-for-the-developer-blog/` does not exist on the site.

I'm guessing that the Table of Contents was converted to a static list before whatever URL change happened, and since it's a static list now, those links need to be updated manually.

**Comment by bph** [comment]
You you are fast, @ryelle - I just added it while I was doing something else to get back to it when I was finished. Thanks for jumping on it! Yep, it doesn't look right. The conversion to static was indeed before the page was published. 
TBH, I hate the implementation of the TOC block in core because it doesn't give me a choice except via conversion to static to get bulleted list instead of numbered list. It shouldn't need a conversion to get bullet list, and get all the links out of sync completely. No user will grasp that. But I digress. 

I'll fix it, when Mary is done editing that page.

**Comment by bph** [comment]
- Removed the TOC block and 
- added it again, 
- converted it to static list, and 
- removed the second and third level of headings. 

Seems to work again.
