### ISSUE TITLE
Consider a visual refresh to match the incoming Developer redesign

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-developer-blog#35]
Extracting from https://github.com/WordPress/wporg-developer-blog/issues/22#issuecomment-1411712302.

The developer site is likely get a refresh in the near future. That could be an opportunity to apply the same theme and design to the dev blog. Here's how that could look:

![Dev blog](https://user-images.githubusercontent.com/1204802/216000388-189a7fc9-b3aa-4346-95fa-2dae00a010f9.png)

[Figma](https://www.figma.com/file/2CKNK5sN7PKNXA4VjVhyqA/Dev-blog?node-id=1111%3A1084&t=d8S1prCk44p6i1ae-1)

The hope would be for this to simplify the dev and design work both. For that reason it would also be smart for this to be a followup to the developer redesign.

**Comment by juanmaguitar** [comment]
@jasmussen is this redesign a requirement to take the Developer Blog out of beta?
Related: https://github.com/WordPress/wporg-developer-blog/issues/2#issuecomment-1425398335

**Comment by jasmussen** [comment]
I don't personally have a strong opinion on the beta label. Whether that gets kept or not, I'm happy to refer to you and others: the content is valid and useful. 

Designwise, the current iteration could strongly benefit from the above approach, so as to feel like a coherent part of the whole. So I would definitely suggest that this should be part of the effort when the general Developer section gets redesigned. It would elevate all the effort poured into the blog itself, and the content that's there. My only concern with removing the beta label would be if that means the larger redesign effort gets paused indefinitely. Because I think it's important we do revisit this. Is that useful?

**Comment by juanmaguitar** [comment]
Thanks @jasmussen for sharing your POV.
I don't have a strong opinion either on the beta label. 

>My only concern with removing the beta label would be if that means the larger redesign effort gets paused indefinitely. 

If keeping it is somehow useful to get this redesign done, I would keep it. 

@bph, I would love to know your thoughts here.

**Comment by bph** [comment]
It depends on the meta team and how they prioritize the work. Does the display of the beta label or not display factor into the decision? 

The Beta Blocker (pun not intended) holds back the marketing team and their efforts to promote the articles on Social Media. They can't do that unless it's officially released. 
And I am all for spreading the word and have more people read them and also get more people involved.

**Comment by bengreeley** [comment]
@bph @juanmaguitar Since we will eventually replace the front page with a design that matches developer.wordpress.org, it doesn't make much sense to invest additional time on the few tasks that were specific to the homepage design tweaks only to redo them shortly thereafter. 

To be clear, the article pages are not slated to have any significant changes, if any, so in my opinion, the site is ready to take out of beta if the primary reason to keep it in beta was to prevent articles from being shared. I think that's ultimately your call about what you feel comfortable doing.

If we want to wait until the new homepage is implemented to take it out of beta, it may be a couple of months before it's prioritized since this site has already had quite a bit of focus from the Meta team, and we'll need to put some focus in additional areas for a bit. Note that the layout will be a little different from the screenshots Joen attached due to visual changes to that page that were requested. We'll see that role out first on developer.wordpress.org and then can discuss when it would make sense to apply on the Developer Blog.

**Comment by bph** [comment]
>If we want to wait until the new homepage is implemented to take it out of beta, it may be a couple of months before it's prioritized  (@bengreeley)

and
>the site is ready to take out of beta if the primary reason to keep it in beta was to prevent articles from being shared (@bengreeley)

What I am reading is: we can take it out of beta, and a visual refresh is on the project list for meta, and it is estimated to being worked on sometime in May or June 2023? 

Yes, the beta label kept marketing from sharing the articles to a larger audience, as there wasn't an official launch of the site, which is the next step, and I added it to my project priorities will start the cross-team collaboration. 

Thanks everyone, for chiming in. I love collaborating with you folks. :-)

**Comment by ndiego** [comment]
This can be closed now that the redesign is complete. See https://github.com/WordPress/wporg-developer-blog/issues/46
